version: '3.8'

services:
  zookeeper:
    build:
      context: .
      dockerfile: Dockerfile-zookeeper
    ports:
      - "2181:2181"

  tests:
    build:
      context: .
      dockerfile: Dockerfile-test
    depends_on:
      - zookeeper
    environment:
      - ZOOKEEPER_HOST=zookeeper
      - ZOOKEEPER_PORT=2181
    command: mvn test
  url-shortener:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - zookeeper
    environment:
      SPRING_PROFILES_ACTIVE: docker
