FROM openjdk:19-jdk AS builder

ENV ZOOKEEPER_VERSION=3.8.4

RUN curl -L "https://downloads.apache.org/zookeeper/zookeeper-${ZOOKEEPER_VERSION}/apache-zookeeper-${ZOOKEEPER_VERSION}-bin.tar.gz" -o /tmp/zookeeper.tar.gz \
    && tar -xzf /tmp/zookeeper.tar.gz -C /opt/ \
    && mv /opt/apache-zookeeper-${ZOOKEEPER_VERSION}-bin /opt/zookeeper \
    && rm /tmp/zookeeper.tar.gz

EXPOSE 2181

WORKDIR /opt/zookeeper

COPY conf/zoo.cfg ./conf/

CMD ["bin/zkServer.sh", "start-foreground"]
